broderjobs/broderjobs/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
# from app.views import error

urlpatterns = [
    #INICIO ESTUDIANTES
    url(r'^', include('main.urls')),

    url(r'^estudiante/', include('estudiante.urls')),

    url(r'^empresa/', include('empresa.urls')),

    url(r'^oportunidad/', include('oportunidad.urls')),

    url(r'^mensaje/', include('mensaje.urls')),

    url(r'^contador_visitas/', include('contador_visitas.urls')),

    url(r'^disc/', include('disc.urls')),

    #ADMIN
    url(r'^brodadminpage/', include(admin.site.urls)),

    url('^', include('django.contrib.auth.urls')),

    #LOGIN WITH SOACIAL
    url(r'^social/', include('social.apps.django_app.urls', namespace='social')),
    url(r'^login-facebook' , 'broderjobs.views.login_facebook', name='login-facebook'),

    url(r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_ROOT, 'show_indexes': settings.DEBUG}),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


handler404 = 'broderjobs.views.error404'

broderjobs/disc/urls.py
from django.conf.urls import patterns, include, url
from . import views

urlpatterns = [
    url(r'^formulario-estudiante/$', 'disc.views.formulario_estudiante', name="disc-formulario-estudiante"),
    url(r'^preguntas-estudiante/$', 'disc.views.preguntas_estudiante', name="disc-preguntas-estudiante"),
    url(r'^respuesta-estudiante/$', 'disc.views.respuesta_estudiante', name="disc-respuesta-estudiante"),
    url(r'^finalizo-estudiante/$', 'disc.views.finalizo_estudiante', name="disc-finalizo-estudiante"),
]

broderjobs/main/urls.py
from django.conf.urls import patterns, include, url
from . import views
from django.contrib.auth import views as auth_views



urlpatterns =[

	url(r'^$' , 'main.views.homepage', name='homepage'),

	url(r'^estudiante/$' , 'main.views.homepage', name='estudiante'),

	url(r'^empresa/$' , 'main.views.homepage_empresa', name='empresa'),

	url(r'^salir/$' , 'django.contrib.auth.views.logout_then_login', name='salir'),

	url(r'^usuarios/$', views.UsuariosView.as_view(), name="usuarios"),

	url(r'^cuenta-editar/$', views.CuentaEditarView.as_view(), name="cuenta-editar"),

	url(r'^cuenta-crear/$', views.CuentaCrearView.as_view(), name="cuenta-crear"),

	url(r'^contrasena-editar/$', 'main.views.contrasena_editar', name="contrasena-editar"),

	# url(r'^contrasena-crear/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
	# 	auth_views.password_reset_confirm, {'template_name': 'main/contrasena-crear.html'}, name="contrasena-crear"),

	url(r'^contrasena-crear/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
		auth_views.password_reset_confirm, {'template_name': 'main/contrasena-restablecer.html',
										'post_reset_redirect' : 'homepage'}, name="contrasena-crear"),

	url(r'^contrasena-recuperar/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
		auth_views.password_reset_confirm, {'template_name': 'main/contrasena-restablecer.html',
										'post_reset_redirect' : 'homepage'}, name="contrasena-recuperar"),

	url(r'^terminos-condiciones/$', 'main.views.terminos_condiciones', name="terminos-condiciones"),

	url(r'^404/$', 'main.views.error404', name="404"),

	# url(r'^editar-cuenta-representante/$', 'main.views.editar_cuenta_representante', name="editar-cuenta-representante"),

	# url(r'^editar-cuenta/$', views.EditarUsuarioEstudianteView.as_view(), name="editar-cuenta"),

	url(r'^universidad-busqueda/$', views.UniversidadBusquedaView.as_view(), name="universidad-busqueda"),

	url(r'^pais-busqueda/$', views.PaisBusquedaView.as_view(), name="pais-busqueda"),

	url(r'^ciudad-busqueda/$', views.CiudadBusquedaView.as_view(), name="ciudad-busqueda"),

	url(r'^carrera-busqueda/$', views.CarreraBusquedaView.as_view(), name="carrera-busqueda"),

	url(r'^carrera-busqueda-por-tipo/$', views.CarreraBusquedaPorTipoView.as_view(), name="carrera-busqueda-por-tipo"),

	url(r'^periodos-graduacion-busqueda/$', views.PeriodosGraduacionBusquedaView.as_view(), name="periodos-graduacion-busqueda"),


]

broderjobs/main/forms.py
# coding=utf-8
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm, PasswordChangeForm
from django.contrib.auth.models import User

from empresa.models import Empresa
from .utils import anos_nacimiento, meses_del_ano, dias_del_mes
import datetime

class CuentaCrearForm(forms.ModelForm):

    class Meta:
        model = User
        fields = ['email', 'first_name', 'last_name' ]


    def clean_email(self):
        email = self.cleaned_data["email"]
        if email is None or email == '':
            raise forms.ValidationError('Email es obligatorio')
        try:
            User._default_manager.get(email=email)
        except User.DoesNotExist:
            return email
        #raise forms.ValidationError(self.error_messages['duplicate_email'])
        raise forms.ValidationError('Email ya esta registrado')


class LoginForm(forms.Form):
    email = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Email', 'class': 'form-control'}))
    password = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Contraseña', 'type':'password', 'class': 'form-control'}))
    remember_me = forms.BooleanField(required=False, widget=forms.CheckboxInput())

class UniqueUserEmailField(forms.EmailField):
    """
    An EmailField which only is valid if no User has that email.
    """
    def validate(self, value):
        super(forms.EmailField, self).validate(value)
        try:
            User.objects.get(email = value)
            raise forms.ValidationError("Email ya esta registrado")
        except User.MultipleObjectsReturned:
            raise forms.ValidationError("Email ya esta registrado")
        except User.DoesNotExist:
            pass

class RegisterForm(UserCreationForm):

    items_anos = anos_nacimiento()
    items_meses = meses_del_ano()
    items_dias = dias_del_mes()

     #Carga items a Grado de Estudio
    # empresas= []
    # for e in Empresa.objects.all():
    #     empresas.append((e.id, e.nombre))
    # items_empresa =[('','Empresa')] + empresas

    empresas_campo = forms.CharField(required = True,  max_length = 50, widget=forms.TextInput(attrs={'placeholder': 'Ingrese una Empresa', 'class': 'form-control'}))
    empresas_hidden = forms.CharField(widget=forms.HiddenInput())

    RUC = forms.CharField(required = True,  max_length = 20, widget=forms.TextInput(attrs={'class': 'form-control'}))


    username = forms.CharField(required = False, max_length = 30, widget=forms.TextInput(attrs={'placeholder': 'username', 'class': 'form-control'}))
    email = UniqueUserEmailField(required = True, widget=forms.TextInput(attrs={'placeholder': 'Email', 'class': 'form-control',}))
    first_name = forms.CharField(required = True, max_length = 30, widget=forms.TextInput(attrs={'placeholder': 'Nombres', 'class': 'form-control'}))
    last_name = forms.CharField(required = True, max_length = 30, widget=forms.TextInput(attrs={'placeholder': 'Apellidos', 'class': 'form-control'}))
    password1 = forms.CharField(required = True, widget=forms.TextInput(attrs={'placeholder': 'Contraseña', 'type':'password', 'class': 'form-control'}))
    password2 = forms.CharField(required = True, widget=forms.TextInput(attrs={'placeholder': 'Confirmar Contraseña', 'type':'password', 'class': 'form-control'}))
    fecha_nacimiento = forms.DateField(required=False)
    ano = forms.ChoiceField(choices=items_anos, required = False, widget=forms.Select(attrs={'class': 'cumpleanos form-control', }))
    mes = forms.ChoiceField(choices=items_meses, required = False, widget=forms.Select(attrs={'class': 'cumpleanos form-control'}))
    dia = forms.ChoiceField(choices=items_dias, required = False, widget=forms.Select(attrs={'class': 'cumpleanos form-control'}))
    telefono = forms.CharField(required = False, max_length = 20, widget=forms.TextInput(attrs={'placeholder': 'Numero telefonico', 'class': 'form-control'}))
    # empresa = forms.ModelChoiceField(queryset=Empresa.objects.all(), empty_label="Empresa",  required = False, widget=forms.Select(attrs={'class': 'form-control'}))

    def __init__(self, *args, **kwargs):
        """
        Changes the order of fields, and removes the username field.
        """
        super(UserCreationForm, self).__init__(*args, **kwargs)
        self.fields.keyOrder = ['email', 'first_name', 'last_name',
                                'password1', 'password2']


    def __generate_username(self, email):
        # TODO: Something more efficient?
        highest_user_id = User.objects.all().order_by('-id')[0].id
        leading_part_of_email = email.split('@',1)[0]
        # leading_part_of_email = re.sub(r'[^a-zA-Z0-9+]', '',
        #                               leading_part_of_email)
        truncated_part_of_email = leading_part_of_email[:3] \
                                  + leading_part_of_email[-3:]
        derived_username = truncated_part_of_email + str(highest_user_id+1)
        return derived_username

    def clean(self, *args, **kwargs):
        """
        Normal cleanup + username generation.
        """
        cleaned_data = super(UserCreationForm, self).clean(*args, **kwargs)
        if cleaned_data.has_key('email'):
            cleaned_data['username'] = self.__generate_username(
                                                        cleaned_data['email'])
        return cleaned_data

    def clean_email(self):
        email = self.cleaned_data["email"]
        try:
            User._default_manager.get(email=email)
        except User.DoesNotExist:
            return email
        #raise forms.ValidationError(self.error_messages['duplicate_email'])
        raise forms.ValidationError('duplicate_email')

    def save(self, commit=True):
        """
        Saves the email, first_name and last_name properties, after the normal
        save behavior is complete.
        """
        user = super(UserCreationForm, self).save(commit)
        if user:
            user.email = self.cleaned_data['email']
            user.first_name = self.cleaned_data['first_name']
            user.last_name = self.cleaned_data['last_name']
            user.set_password(self.cleaned_data['password1'])
            if commit:
                user.save()
        return user

class RegistroRepresentanteForm(UserCreationForm):

    username = forms.CharField(required = False, max_length = 30, widget=forms.TextInput(attrs={'placeholder': 'username'}))
    email = UniqueUserEmailField(required = True, widget=forms.TextInput(attrs={'placeholder': 'Email'}))
    first_name = forms.CharField(required = True, max_length = 30, widget=forms.TextInput(attrs={'placeholder': 'Nombres'}))
    last_name = forms.CharField(required = True, max_length = 30, widget=forms.TextInput(attrs={'placeholder': 'Apellidos'}))
    password1 = forms.CharField(required = True, max_length = 10, widget=forms.TextInput(attrs={'placeholder': 'Contraseña', 'type':'password'}))
    password2 = forms.CharField(required = True, max_length = 10, widget=forms.TextInput(attrs={'placeholder': 'Confirmar Contraseña', 'type':'password'}))
    telefono = forms.CharField(required = False, max_length = 20, widget=forms.TextInput(attrs={'placeholder': 'Numero telefonico'}))
    empresa = forms.ModelChoiceField(queryset=Empresa.objects.all(), empty_label="Empresa",  required = False)

    def __init__(self, *args, **kwargs):
        super(UserCreationForm, self).__init__(*args, **kwargs)
        self.fields.keyOrder = ['email', 'first_name', 'last_name',
                                'password1', 'password2']


    def __generate_username(self, email):
        # TODO: Something more efficient?
        highest_user_id = User.objects.all().order_by('-id')[0].id
        leading_part_of_email = email.split('@',1)[0]
        truncated_part_of_email = leading_part_of_email[:3] \
                                  + leading_part_of_email[-3:]
        derived_username = truncated_part_of_email + str(highest_user_id+1)
        return derived_username

    def clean(self, *args, **kwargs):
        cleaned_data = super(UserCreationForm, self).clean(*args, **kwargs)
        if cleaned_data.has_key('email'):
            cleaned_data['username'] = self.__generate_username(
                                                        cleaned_data['email'])
        return cleaned_data

    def clean_email(self):
        email = self.cleaned_data["email"]
        try:
            User._default_manager.get(email=email)
        except User.DoesNotExist:
            return email
        raise forms.ValidationError('duplicate_email')

    def save(self, commit=True):
        user = super(UserCreationForm, self).save(commit)
        if user:
            user.email = self.cleaned_data['email']
            user.first_name = self.cleaned_data['first_name']
            user.last_name = self.cleaned_data['last_name']
            user.set_password(self.cleaned_data['password1'])
            if commit:
                user.save()
        return user

class EditarUsuarioForm( PasswordChangeForm ):

    new_password1 = forms.CharField(required = True, max_length = 10, widget=forms.TextInput(attrs={'placeholder': 'Escriba su nueva Contraseña', 'type':'password', 'class':'half'}))
    new_password2 = forms.CharField(required = True, max_length = 10, widget=forms.TextInput(attrs={'placeholder': 'Escriba otra vez su nueva contraseña', 'type':'password', 'class':'half'}))
    old_password = forms.CharField(required = True, max_length = 10, widget=forms.TextInput(attrs={'placeholder': 'Escriba su contraseña actual', 'type':'password', 'class':'half'}))

class CuentaEditarForm(forms.Form):
    first_name = forms.CharField(required = True, max_length = 30, widget=forms.TextInput(attrs={'placeholder': 'Nombres'}))
    last_name = forms.CharField(required = True, max_length = 30, widget=forms.TextInput(attrs={'placeholder': 'Apellidos'}))
    email = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Email'}))

broderjobs/templates/main/contrasena-editar.html
{% extends  tipo|yesno:"empresa/base.html,estudiante/base.html" %}
{%block css%}
{%endblock%}
{% block content %}
{% load staticfiles %}
<script src="{% static 'js/jquery.validate.min.js' %}"></script>
<script src="{% static 'js/additional-methods.min.js' %}"></script>




<section class="usuarios">
    <div class="centered">
        <div class="panel left principal">
            <div class="box">
			    <div class="content">
                    <section class="pos-relative">
                       <form action="" method="post">{%csrf_token%}
                            <h3 class="title"><i class="info"></i>Cambio de Contraseña</h3>
                            <input type="submit" value="GUARDAR" class="btn-action">
                           {%if message%}
                                <p>{{message}}</p>
                           {%endif%}
                            <div class="detalle col-3-7">
                                {%if form.errors %}
								<div class="alert alert-warning alert-dismissible" role="alert">
									<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>
									{{ form.first_name.errors }}
									{{ form.last_name.errors }}
									{{ form.email.errors }}
                                    {{ form.telefono.errors }}

								</div>
								{% endif%}
                                <div>
                                    <label>Contrase&ntilde;a actual</label>
                                    <p><!--<input class="half" type="text" placeholder="Escriba su contrase&ntilde;a actual" />-->
                                        {{form.old_password}}
                                    </p>
                                    <div class="clear"></div>
                                </div>
                                <div>
                                    <label>Contrase&ntilde;a nueva</label>
                                    <p>{{form.new_password1}}
                                        <!--<input class="half" type="text" placeholder="Escriba su nueva contrase&ntilde;a" />-->
                                    </p>
                                    <div class="clear"></div>
                                </div>
                                <div>
                                    <label>Confirmar contrase&ntilde;a</label>
                                    <p>
                                        {{form.new_password2}}
                                        <!--<input class="half" type="text" placeholder="Escriba otra vez su nueva contrase&ntilde;a" />-->
                                    </p>
                                    <div class="clear"></div>
                                </div>
                            </div>
                           <!--{{form.as_p}}<input type="submit" value="Update &rarr;">-->
                        </form>

                    </section>
				</div>
            </div>
        </div>
        <div class="clear"></div>
    </div>
</section>
{% endblock content%}
{% block js %}
<script>
    $(function(){
        /*$("input[type=submit]").on("click", function(e){
            e.preventDefault();
            debugger;
        });*/
        $("input:not([type=submit])").addClass("form-control");
        $("form").validate({
            errorPlacement: function (error, element) {
                $(element).tooltip('destroy');
                $(element).tooltip({
                    animation: true,
                    placement: "right",
                    title: $(error).text(),
                    trigger: "manual"
                } );
                $(element).tooltip('show');
            },
            success: function (label, element) {
                $(element).tooltip('hide');
            },
            rules: {
                "old_password": { required: true, minlength: 6 },
                "new_password1": { required: true, minlength: 6 },
                "new_password2": { required: true, minlength: 6, equalTo: "#id_new_password1" },
            },
            messages: {
                "old_password": { 	required: "Este campo es obligatorio",
									minlength: "La contraseña debe tener al menos seis (6) caracteres"},
                "new_password1": {  required: "Este campo es obligatorio",
									minlength: "La contraseña debe tener al menos seis (6) caracteres"},
                "new_password2": {  required: "Este campo es obligatorio",
                                    minlength: "La contraseña debe tener al menos seis (6) caracteres",
									equalTo: "Las contraseñas deben ser iguales" },
            }
        });
    });
</script>
{% endblock %}

broderjobs/templates/main/cuenta-crear.html
{% extends  tipo|yesno:"empresa/base.html,estudiante/base.html" %}
{%block css%}
{%endblock%}
{% block content %}
{% load staticfiles %}
<script src="{% static 'js/jquery.validate.min.js' %}"></script>
<script src="{% static 'js/additional-methods.min.js' %}"></script>
<style>
    .tooltip-inner { width: 100px;}
</style>
<section class="usuarios">
    <div class="centered">
        <div class="panel left principal">
            <div class="box">
			    <div class="content">
                    <section class="pos-relative">
                       <form action="" method="post">{%csrf_token%}
                            <h3 class="title"><i class="info"></i>Usuario Nuevo</h3>
                            <input type="submit" value="GUARDAR" class="btn-action">

                            {%if form.errors %}
                            <div class="alert alert-warning alert-dismissible" role="alert">
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>
                                {{ form.first_name.errors }}
								{{ form.last_name.errors }}
								{{ form.email.errors }}
                            </div>
                            {% endif%}
                            <div class="detalle col-3-7">
                                <div>
                                    <label>Nombres</label>
                                    <p>
                                        {{form.first_name}}
                                    </p>
                                    <div class="clear"></div>
                                </div>
                                <div>
                                    <label>Apellidos</label>
                                    <p>{{form.last_name}}
                                    </p>
                                    <div class="clear"></div>
                                </div>
{#                                <div>#}
{#                                    <label>Teléfono</label>#}
{#                                    <p>#}
{#                                        {{form.telefono}}#}
{##}
{#                                    </p>#}
{#                                    <div class="clear"></div>#}
{#                                </div>#}
                                <div>
                                    <label>Correo</label>
                                    <p>
                                        {{form.email}}
                                    </p>
{#                           {{ form.as_p }}#}
                                    <label class="indicacion">*Con este correo iniciara sesion</label>
                                    <div class="clear"></div>
                                </div>

                            </div>

                        </form>

                    </section>
				</div>
            </div>
        </div>
        <div class="clear"></div>
    </div>
</section>
{% endblock content%}
{% block js %}
<script>
    $(function(){
        /*$("input[type=submit]").on("click", function(e){
            e.preventDefault();
            debugger;
        });*/
        $("input:not([type=submit])").addClass("form-control");
        $("form").validate({
            errorPlacement: function (error, element) {
                $(element).tooltip('destroy');
                $(element).tooltip({
                    animation: true,
                    placement: "right",
                    title: $(error).text(),
                    trigger: "manual"
                } );
                $(element).tooltip('show');
            },
            success: function (label, element) {
                $(element).tooltip('hide');
            },
            rules: {
                "email": { required: true, minlength: 6 },
                "first_name": { required: true, pattern: /^([^\d]*)$/},
                "last_name": { required: true, pattern: /^([^\d]*)$/ }
            },
            messages: {
                "email": { 	required: "Este campo es obligatorio",
                            email: "Introduzca un correo válido"},
                "first_name": {
                    required: "Este campo es obligatorio",
                    pattern: "Este campo no permite caracteres numéricos" },
                "last_name": {
                    required: "Este campo es obligatorio",
                    pattern: "Este campo no permite caracteres numéricos" }
            }
        });
    });
</script>
{% endblock %}

broderjobs/templates/main/cuenta-editar.html
{% extends  tipo|yesno:"empresa/base.html,estudiante/base.html" %}
{%block css%}
{%endblock%}
{% block content %}
{% load staticfiles %}
<script src="{% static 'js/jquery.validate.min.js' %}"></script>
<script src="{% static 'js/additional-methods.min.js' %}"></script>




<section class="usuarios">
    <div class="centered">
        <div class="panel left principal">
            <div class="box">
			    <div class="content">
                    <section class="pos-relative">
                       <form action="" method="post">{%csrf_token%}
                            <h3 class="title"><i class="info"></i>Mi cuenta</h3>
                            <input type="submit" value="GUARDAR" class="btn-action">
                           {%if message%}
                                <p>{{message}}</p>
                           {%endif%}
                            <div class="detalle col-3-7">
                                <div>
                                    <label>Nombres</label>
                                    <p>
                                        {{form.first_name}}
                                    </p>
                                    <div class="clear"></div>
                                </div>
                                <div>
                                    <label>Apellidos</label>
                                    <p>{{form.last_name}}
                                    </p>
                                    <div class="clear"></div>
                                </div>
                                <div>
                                    <label>Correo</label>
                                    <p>
                                        {{form.email}}
                                    </p>
                                    <label class="indicacion">*Con este correo iniciara sesion</label>
                                    <div class="clear"></div>
                                </div>
                                <div>
                                    <label>Teléfono</label>
                                    <p>
                                        {{form.telefono}}

                                    </p>
                                    <div class="clear"></div>
                                </div>
                            </div>
                        </form>

                    </section>
				</div>
            </div>
        </div>
        <div class="clear"></div>
    </div>
</section>
{% endblock content%}
{% block js %}
<script>
    $(function(){
        /*$("input[type=submit]").on("click", function(e){
            e.preventDefault();
            debugger;
        });*/
        $("input:not([type=submit])").addClass("form-control");
        $("form").validate({
            errorPlacement: function (error, element) {
                $(element).tooltip('destroy');
                $(element).tooltip({
                    animation: true,
                    placement: "right",
                    title: $(error).text(),
                    trigger: "manual"
                } );
                $(element).tooltip('show');
            },
            success: function (label, element) {
                $(element).tooltip('hide');
            },
            rules: {
                "old_password": { required: true, minlength: 6 },
                "new_password1": { required: true, minlength: 6 },
                "new_password2": { required: true, minlength: 6, equalTo: "#id_new_password1" },
            },
            messages: {
                "old_password": { 	required: "Este campo es obligatorio",
									minlength: "La contraseña debe tener al menos seis (6) caracteres"},
                "new_password1": {  required: "Este campo es obligatorio",
									minlength: "La contraseña debe tener al menos seis (6) caracteres"},
                "new_password2": {  required: "Este campo es obligatorio",
                                    minlength: "La contraseña debe tener al menos seis (6) caracteres",
									equalTo: "Las contraseñas deben ser iguales" },
            }
        });
    });
</script>
{% endblock %}

broderjobs/templates/main/empresa_login.html
{% extends 'main/index_empresa.html' %}
{% block content_empresa %}

        {%if message %}
        <b>{{message}}</b>
        {% endif%}
        <form action="" method="post">{%csrf_token%}
            <div class="login active" id="login">
					<div class="content">
						<label class="ingresa-email">Iniciar Sesi&oacute;n</label>
						<div class="datos">
                            {{ form.username }}
		                    {{ form.password }}
							<input type="text" placeholder="E-mail" />
							<input type="password" placeholder="Contrase&ntilde;a" />
						</div>
						<div class="opciones">
							<input type="checkbox" id="recordarme" /><label for="recordarme">Recordarme.</label>
							<a>¿Olvidaste tu contrase&ntilde;a?</a>
						</div>
						<a class="ingresar" href="oportunidades.html">INGRESAR</a>
						<div class="division">
							<div class="full line"></div>
							<div class="clear"></div>
						</div>
						<a class="registrate" onclick="desactivar('mensaje-central'); desactivar('login'); activar('registro');">¿No est&aacute;s registrado? Reg&iacute;strate AQU&Iacute;.</a>
						<input type="submit" name="form" value="Submit" class="Ingresar" text="Ingresar" />
                        <a class="close" onclick="desactivar('login'); activar('mensaje-central');">x</a>
					</div>
				</div>
        </form>
{% endblock%}

broderjobs/templates/main/empresa_registro.html
{% extends 'main/index_empresa.html' %}
{% block content_empresa %}

        {%if message %}
        <b>{{message}}</b>
        {% endif%}
        <form action="" method="post">{%csrf_token%}
           <div class="login active" id="registro">
					<div class="content">
						<label class="saludo"></label>
						<a class="registrate">Reg&iacute;strate con tu e-mail</a>
						<div class="datos registro">
							<input type="text" placeholder="Nombres" />
							<input type="text" placeholder="Apellidos" />
							<input type="text" placeholder="E-mail" />
							<input type="text" placeholder="Nombre de la Empresa" />
							<input type="text" placeholder="N&uacute;mero telef&oacute;nico" />
							<input type="password" placeholder="Contrase&ntilde;a" />
							<input type="password" placeholder="Confirmar contrase&ntilde;a" />
					    </div>
					    <div class="opciones">
					        <input type="checkbox" id="acepto" /><label for="acepto">Acepto los <a class="terminos-condiciones" href="../static/terminos_y_condiciones.html">T&eacute;rminos y condiciones, y Pol&iacute;ticas de Privacidad de BRODER</a>.</label>
					    </div>
					    <a class="registrarme" href="oportunidades.html">REGISTRARME</a>
					    <a class="close" onclick="desactivar('registro'); activar('mensaje-central');">x</a>
			    </div>
           </div>
        </form>
{% endblock%}