broderjobs/broderjobs/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
# from app.views import error

urlpatterns = [
    #INICIO ESTUDIANTES
    url(r'^', include('main.urls')),

    url(r'^estudiante/', include('estudiante.urls')),

    url(r'^empresa/', include('empresa.urls')),

    url(r'^oportunidad/', include('oportunidad.urls')),

    url(r'^mensaje/', include('mensaje.urls')),

    url(r'^contador_visitas/', include('contador_visitas.urls')),

    url(r'^disc/', include('disc.urls')),

    #ADMIN
    url(r'^brodadminpage/', include(admin.site.urls)),

    url('^', include('django.contrib.auth.urls')),

    #LOGIN WITH SOACIAL
    url(r'^social/', include('social.apps.django_app.urls', namespace='social')),
    url(r'^login-facebook' , 'broderjobs.views.login_facebook', name='login-facebook'),

    url(r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_ROOT, 'show_indexes': settings.DEBUG}),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


handler404 = 'broderjobs.views.error404'

broderjobs/disc/urls.py
from django.conf.urls import patterns, include, url
from . import views

urlpatterns = [
    url(r'^formulario-estudiante/$', 'disc.views.formulario_estudiante', name="disc-formulario-estudiante"),
    url(r'^preguntas-estudiante/$', 'disc.views.preguntas_estudiante', name="disc-preguntas-estudiante"),
    url(r'^respuesta-estudiante/$', 'disc.views.respuesta_estudiante', name="disc-respuesta-estudiante"),
    url(r'^finalizo-estudiante/$', 'disc.views.finalizo_estudiante', name="disc-finalizo-estudiante"),
]

broderjobs/empresa/urls.py
from django.conf.urls import patterns, include, url
from . import views

urlpatterns = [
    # url(r'^oportunidad-listar/', views.OportunidadListarView.as_view(), name='empresa-oportunidad-listar'),
    # url(r'^oportunidad-listar/', 'empresa.views.oportunidad_listar', name='empresa-oportunidad-listar'),

    # url(r'^oportunidad-busqueda/$', views.OportunidadBusquedaView.as_view(), name="empresa-oportunidad-busqueda"),

    # url(r'^oportunidad-detalle/(?P<id>\d+)/$', views.OportunidadDetalleView.as_view(), name="empresa-oportunidad-detalle"),

    url(r'^mi-empresa/$', views.MiEmpresaView.as_view(), name="mi-empresa"),

    url(r'^mi-empresa/info-general/$', views.InfoGeneralView.as_view(), name="mi-empresa-info-general"),

    url(r'^mi-empresa/logo/$', views.LogoView.as_view(), name="mi-empresa-logo"),

    url(r'^mi-empresa/ubicacion/$', views.UbicacionView.as_view(), name="mi-empresa-ubicacion"),

    url(r'^mi-empresa/redes-sociales/$', views.RedesSocialesView.as_view(), name="mi-empresa-redes-sociales"),

    url(r'^oportunidades/', 'empresa.views.oportunidades', name='empresa-oportunidad-lista'),

    url(r'^oportunidad-listar/', 'empresa.views.oportunidades_listar', name='empresa-oportunidad-listar'),

    url(r'^oportunidad-busqueda/$', 'empresa.views.oportunidad_busqueda', name="empresa-oportunidad-busqueda"),

    url(r'^oportunidad-cargar-lista/$', 'empresa.views.oportunidad_cargar_lista', name="empresa-oportunidad-cargar-lista"),

    url(r'^oportunidad-buscar/$', views.OportunidadBuscarView.as_view(), name="empresa-oportunidad-buscar"),

    url(r'^oportunidad-postulaciones/$', views.OportunidadPostulacionesView.as_view(), name="empresa-oportunidad-postulaciones"),

    url(r'^oportunidad-estudiantes/$', views.OportunidadEstudiantes.as_view(), name="empresa-oportunidad-estudiantes"),

    url(r'^oportunidad-candidatos/(?P<id>\d+)/$', views.OportunidadCandidatos.as_view(), name="empresa-oportunidad-candidatos"),

    url(r'^oportunidad-candidatos/(?P<id>\d+)/cv/(?P<e>\d+)$', views.OportunidadCandidatosCV.as_view(), name="empresa-oportunidad-candidatos-cv"),

    url(r'^candidato-cv-pdf/$', 'empresa.views.canditado_cv_pdf', name="empresa-candidato-cv-pdf"),

    url(r'^mi-empresa/slider-imagenes/(?P<id>\d+)/$', 'empresa.views.empresa_slider_imagenes', name="empresa-slider-imagenes"),
    url(r'^mi-empresa/delete/(?P<pk>\d+)$', views.PictureDeleteView.as_view(), name='upload-delete'),
    url(r'^mi-empresa/imagenes/$', views.PictureCreateView.as_view(), name='upload-new'),
    url(r'^mi-empresa/imagenes/view/$', views.PictureListView.as_view(), name='upload-view'),

    url(r'^mi-empresa/video-delete/$', 'empresa.views.video_url_delete', name='empresa-video-delete'),
    url(r'^mi-empresa/video-create/$','empresa.views.video_url_create', name='empresa-video-create'),
    url(r'^mi-empresa/video-list/view/$', 'empresa.views.video_url_list', name='empresa-video-list'),
    url(r'^mi-empresa/videos/$', views.VideosListView.as_view(), name='videos-list'),

    url(r'^prueba/$','empresa.views.prueba', name='prueba'),
    url(r'^prueba_empresa/$','empresa.views.prueba_empresa', name='prueba_empresa'),

    url(r'^empresa-busqueda/$', views.EmpresaBusquedaView.as_view(), name="empresa-busqueda"),

]

handler404 = 'app.views.404_view'

broderjobs/empresa/models.py
from django.db import models
from django.contrib.auth.models import User
from main.models import Persona, Pais, Ciudad, GradoEstudio, Universidad, Carrera, TipoPuesto, CargaHoraria, Idioma,\
    Conocimiento
from main import utils
from datetime import date, datetime
from broderjobs.settings import STATIC_URL

items_registro = utils.estado_registro()


class Sector(models.Model):
    descripcion = models.CharField(max_length="50")
    fecha_creacion = models.DateField(default=datetime.now, null=True, blank=True)
    fecha_modificacion = models.DateField(default=datetime.now, null=True, blank=True)
    estado =  models.CharField(choices=items_registro, max_length=1, default='A', null=True, blank=True)
    orden = models.IntegerField(null= True, blank= True)

    class Meta:
        ordering = ["descripcion"]

    def __unicode__(self):
        return self.descripcion

class Puesto(models.Model):
    descripcion = models.CharField(max_length="50")

    orden = models.IntegerField(null= True, blank= True)
    fecha_creacion = models.DateField(default=datetime.now, null=True, blank=True)
    fecha_modificacion = models.DateField(default=datetime.now, null=True, blank=True)
    estado =  models.CharField(choices=items_registro, max_length=1, default='A', null=True, blank=True)

    class Meta:
        ordering = ["orden"]

    def __unicode__(self):
        return self.descripcion

class NumeroFuncionarios(models.Model):
    descripcion = models.CharField(max_length="50")

    fecha_creacion = models.DateField(default=datetime.now, null=True, blank=True)
    fecha_modificacion = models.DateField(default=datetime.now, null=True, blank=True)
    estado =  models.CharField(choices=items_registro, max_length=1, default='A', null=True, blank=True)
    orden = models.IntegerField(null= True, blank= True)
    class Meta:
        ordering = ["orden"]

    def __unicode__(self):
        return self.descripcion

class FacturacionAnual(models.Model):
    descripcion = models.CharField(max_length="50")

    fecha_creacion = models.DateField(default=datetime.now, null=True, blank=True)
    fecha_modificacion = models.DateField(default=datetime.now, null=True, blank=True)
    estado =  models.CharField(choices=items_registro, max_length=1, default='A', null=True, blank=True)
    orden = models.IntegerField(null= True, blank= True)
    class Meta:
        ordering = ["orden"]

    def __unicode__(self):
        return self.descripcion

class CategoriaEmpresa(models.Model):

    descripcion = models.CharField(max_length="50")

    fecha_creacion = models.DateField(default=datetime.now, null=True, blank=True)
    fecha_modificacion = models.DateField(default=datetime.now, null=True, blank=True)
    estado =  models.CharField(choices=items_registro, max_length=1, default='A', null=True, blank=True)
    orden = models.IntegerField(null= True, blank= True)
    class Meta:
        ordering = ["orden"]

    def __unicode__(self):
        return unicode(self.persona) or u''

class Empresa(models.Model):

    nombre =  models.CharField(max_length="1000", default=None, null=True, blank=True )
    descripcion = models.CharField(max_length="200", default=None, null=True, blank=True )
    quienes_somos = models.CharField(max_length="1000", default=None, null=True, blank=True )
    telefono = models.CharField(max_length="100", default=None, null=True, blank=True )
    RUC = models.CharField(max_length="20", default=None, null=True, blank=True )
    sector = models.ForeignKey(Sector, default=None, null=True, blank=True )
    numero_funcionarios = models.ForeignKey(NumeroFuncionarios, default=None, null=True, blank=True)
    facturacion_anual = models.ForeignKey(FacturacionAnual, default=None, null=True, blank=True)
    ano_fundacion =  models.CharField(max_length="10", default=None, null=True, blank=True )
    pais = models.ForeignKey(Pais, default=None, null=True, blank=True )
    ciudad = models.ForeignKey(Ciudad, default=None, null=True, blank=True )
    website = models.CharField(max_length="50", default=None, null=True, blank=True )
    logo = models.ImageField('logo', upload_to='img/%Y/%m/%d', null=True, blank=True)
    direccion_map = models.CharField(max_length="100", default=None, null=True, blank=True)
    longitud = models.FloatField(verbose_name='longitud', default=None, null=True, blank=True )
    latitud = models.FloatField(verbose_name='latitud', default=None, null=True, blank=True )

    orden = models.IntegerField(null= True, blank= True)
    usuario_creacion = models.CharField(max_length="50", default=None, null=True, blank=True)
    fecha_creacion = models.DateField(default=datetime.now, null=True, blank=True)
    usuario_modificacion = models.CharField(max_length="50", default=None, null=True, blank=True)
    fecha_modificacion = models.DateField(default=datetime.now, null=True, blank=True)
    estado =  models.CharField(choices=items_registro, max_length=1, default='A', null=True, blank=True)


    def __unicode__(self):
        return unicode(self.nombre) or u''

    @property
    def set_logo(self):
        if self.logo:
            return self.logo.url
        else:
            return STATIC_URL+"img/profile/profile_default.png"

    class Meta:
        ordering = ["orden"]

class Representante(models.Model):

    persona = models.OneToOneField(Persona)
    empresa = models.ForeignKey(Empresa)
    administrador = models.BooleanField(default=False, blank=True)

    usuario_creacion = models.CharField(max_length="50", default=None, null=True, blank=True)
    fecha_creacion = models.DateField(default=datetime.now, null=True, blank=True)
    usuario_modificacion = models.CharField(max_length="50", default=None, null=True, blank=True)
    fecha_modificacion = models.DateField(default=datetime.now, null=True, blank=True)
    estado =  models.CharField(choices=items_registro, max_length=1, default='A', null=True, blank=True)

    def __unicode__(self):
        return unicode(self.persona) or u''

class EvaluacionEmpresa(models.Model):

    empresa = models.ForeignKey(Empresa)
    usuario = models.ForeignKey(User)
    linea_carrera = models.FloatField(default=None, null=True, blank=True )
    flexibilidad_horarios = models.FloatField(default=None, null=True, blank=True )
    ambiente_trabajo = models.FloatField(default=None, null=True, blank=True )
    salarios = models.FloatField(default=None, null=True, blank=True )
    ranking = models.FloatField(default=None, null=True, blank=True )

    usuario_creacion = models.CharField(max_length="50", default=None, null=True, blank=True)
    fecha_creacion = models.DateField(default=datetime.now, null=True, blank=True)
    usuario_modificacion = models.CharField(max_length="50", default=None, null=True, blank=True)
    fecha_modificacion = models.DateField(default=datetime.now, null=True, blank=True)
    estado =  models.CharField(choices=items_registro, max_length=1, default='A', null=True, blank=True)

    def __unicode__(self):
        return unicode((self.empresa)) or u''

class RankingEmpresa(models.Model):

    empresa = models.ForeignKey(Empresa)
    linea_carrera = models.FloatField(default=None, null=True, blank=True )
    flexibilidad_horarios = models.FloatField(default=None, null=True, blank=True )
    ambiente_trabajo = models.FloatField(default=None, null=True, blank=True )
    salarios = models.FloatField(default=None, null=True, blank=True )
    ranking_general = models.FloatField(default=None, null=True, blank=True )

    usuario_creacion = models.CharField(max_length="50", default=None, null=True, blank=True)
    fecha_creacion = models.DateField(default=datetime.now, null=True, blank=True)
    usuario_modificacion = models.CharField(max_length="50", default=None, null=True, blank=True)
    fecha_modificacion = models.DateField(default=datetime.now, null=True, blank=True)
    estado =  models.CharField(choices=items_registro, max_length=1, default='A', null=True, blank=True)

    def __unicode__(self):
        return unicode(self.empresa) or u''

class Empresa_Imagenes(models.Model):

    empresa = models.ForeignKey(Empresa, default=None, null=True, blank=True)
    file = models.ImageField(upload_to='img/%Y/%m/%d', default=None, null=True, blank=True)
    slug = models.SlugField(max_length=50, blank=True)

    usuario_creacion = models.CharField(max_length="50", default=None, null=True, blank=True)
    fecha_creacion = models.DateField(default=datetime.now, null=True, blank=True)
    usuario_modificacion = models.CharField(max_length="50", default=None, null=True, blank=True)
    fecha_modificacion = models.DateField(default=datetime.now, null=True, blank=True)
    estado =  models.CharField(choices=items_registro, max_length=1, default='A', null=True, blank=True)

    def __unicode__(self):
        return self.file.name

    @models.permalink
    def get_absolute_url(self):
        return ('upload-new', )

    def save(self, *args, **kwargs):
        self.slug = self.file.name
        super(Empresa_Imagenes, self).save(*args, **kwargs)

    def delete(self, *args, **kwargs):
        """delete -- Remove to leave file."""
        self.file.delete(False)
        super(Empresa_Imagenes, self).delete(*args, **kwargs)

    # @property
    # def set_imagen(self):
    #     if self.imagen:
    #         return self.imagen.url
    #     else:
    #         return "/static/img/profile/profile_default.png"

class Picture(models.Model):
    """This is a small demo using just two fields. The slug field is really not
    necessary, but makes the code simpler. ImageField depends on PIL or
    pillow (where Pillow is easily installable in a virtualenv. If you have
    problems installing pillow, use a more generic FileField instead.

    """
    file = models.ImageField(upload_to="pictures")
    slug = models.SlugField(max_length=50, blank=True)
    empresa = models.ForeignKey(Empresa, default=None, null=True, blank=True)

    def __unicode__(self):
        return self.slug

broderjobs/empresa/forms.py
# coding=utf-8
from django import forms
from models import Empresa, Representante, Sector, EvaluacionEmpresa, Pais

class InfoGeneralForm(forms.ModelForm):

    ciudad_hidden = forms.CharField(widget=forms.HiddenInput(),required=False)
    pais = forms.ModelChoiceField(queryset=Pais.objects.all(), empty_label="Pais", required = False, widget=forms.Select(attrs={'class': 'full', }))

    class Meta:
        model = Empresa
        fields = ('nombre', 'RUC', 'quienes_somos', 'sector', 'numero_funcionarios', 'facturacion_anual', 'ano_fundacion',
                  'website','telefono')
        widget = {
            'quienessomos': forms.widgets.Textarea(),
        }


class LogoForm(forms.Form):
     logo = forms.ImageField(required=False, error_messages = {'invalid':'Porfavor seleccione una Imagen valida'}, widget=forms.FileInput)

class UbicacionForm(forms.ModelForm):
    class Meta:
        model = Empresa
        fields = ('longitud', 'latitud', 'direccion_map')

class RedesSocialesForm(forms.Form):
    facebook = forms.CharField(required=False, max_length=200, widget=forms.TextInput(attrs={
                                                                            'placeholder': 'Ingrese direccion de facebook',
                                                                            'class': 'form-control'}))
    twitter = forms.CharField(required=False, max_length=200, widget=forms.TextInput(attrs={
                                                                            'placeholder': 'Ingrese direccion de twitter',
                                                                            'class': 'form-control'}))
    linkedin = forms.CharField(required=False, max_length=200, widget=forms.TextInput(attrs={
                                                                            'placeholder': 'Ingrese direccion de linkedin',
                                                                            'class': 'form-control'}))

broderjobs/templates/empresa/mi-empresa-info-general.html
<style>
	.tooltip {
		width: 167px;
	}

	.tooltip-arrow{
		top: 44.1754%;
	}
</style>

<div style="margin:0 50px">
	<form id = "empresa-info_general" class="form-horizontal" action="{% url 'mi-empresa-info-general' %}" method="post">{%csrf_token%}
		<div class = "form-group">
			<label class = "control-label bold col-sm-3">Nombre comercial *</label>
			<div class = "col-sm-9">
				{{ form.nombre }}
			</div>
		</div>
		<div class = "form-group">
			<label class = "control-label bold col-sm-3">Quienes somos *</label>
			<div class = "col-sm-9">
				<textarea id = "txt-quienes_somos" name="quienes_somos_clone"></textarea>
					{{ form.quienes_somos }}
			</div>
		</div>

		<div class = "form-group">
			<label class = "control-label bold col-sm-3">RUC *</label>
			<div class = "col-sm-9">
				{{ form.RUC }}
				<label class="descripcion">Este campo es privado y no es visible para los candidatos.</label>
			</div>
		</div>
		<div class = "form-group">
			<label class = "control-label bold col-sm-3">Teléfono *</label>
			<div class = "col-sm-9">
				{{ form.telefono }}
				<label class="descripcion">Este campo es privado y no es visible para los candidatos.</label>
			</div>
		</div>
		<div class = "form-group">
			<label class = "control-label bold col-sm-3">Sector</label>
			<div class = "col-sm-9">
				{{ form.sector }}
			</div>
		</div>
		<div class = "form-group">
			<label class = "control-label bold col-sm-3">Número de funcionarios</label>
			<div class = "col-sm-9">
				{{ form.numero_funcionarios }}
			</div>
		</div>
		<div class = "form-group">
			<label class = "control-label bold col-sm-3">Facturación anual</label>
			<div class = "col-sm-9">
				{{ form.facturacion_anual }}
			</div>
		</div>
		<div class = "form-group">
			<label class = "control-label bold col-sm-3">Año de Fundación</label>
			<div class = "col-sm-9">
				{{ form.ano_fundacion }}
			</div>
		</div>
		<div class = "form-group">
			<label class = "control-label bold col-sm-3">Sede Global</label>
			<div class = "col-sm-4">
				{{ form.pais }}
			</div>
			<div class = "col-sm-5">
				<select class="full" id="id_ciudad"></select>
				{{form.ciudad_hidden}}
				<!--{{ form.ciudad }}-->

			</div>
		</div>
		<div class = "form-group">
			<label class = "control-label bold col-sm-3">Website</label>
			<div class = "col-sm-9">
				{{ form.website }}
			</div>
		</div>

		<!--<input type="submit" class="btn btn-submit col-md-offset-2">-->
	</form>
</div>
<script>
	$(function(){
        $("#empresa-info_general input").addClass("form-control");
		$("#empresa-info_general select").addClass("form-control");
		$("#empresa-info_general textarea").addClass("form-control");
		$("#txt-quienes_somos").val($("#id_quienes_somos").val());
		$("#id_quienes_somos").hide();

        $('textarea').each(function(){
            $(this).after("<div class = 'textarea-feedback'></div>");
            var enteredText = $(this).val();
            var numberOfLineBreaks = (enteredText.match(/\n/g)||[]).length
            var characterCount = enteredText.length + numberOfLineBreaks;

            var totalText = 1000 - characterCount;
            $(this).next().html(totalText + ' caracteres');
        });

        $('textarea').on("keyup", function() {
            var enteredText = $(this).val();
            var numberOfLineBreaks = (enteredText.match(/\n/g)||[]).length;
            var characterCount = enteredText.length + numberOfLineBreaks;

            var totalText = 1000 - characterCount;
            $(this).next().html(totalText + ' caracteres');
        });

		$('#id_website').prop( "placeholder", 'Ej: www.example.com' );

		InicializarSelect2();

		$("#txt-quienes_somos").on("input", function(){
			$("#id_quienes_somos").val($("#txt-quienes_somos").val());
		});
		$("#form-modal .modal-title").html('<i class="business"></i>Sobre la empresa');

		$.validator.addMethod('checkurl',function(value, element, param){

            if( !(value.substr(0,7) == 'http://' || value.substr(0,8) == 'https://') ){
                value = 'http://' + value;
            }

            if(value.substr(value.length-1, 1) != '/'){
                value = value + '/';
            }
            return this.optional(element) || /^(http|https|ftp):\/\/[a-z0-9]+([\-\.]{1}[a-z0-9]+)*\.[a-z]{2,5}(:[0-9]{1,5})?(\/.*)?$/i.test(value);
		},'URL inválida');

        /*
        $.validator.addMethod("cus_url", function(value, element) {
    if(value.substr(0,7) != 'http://'){
        value = 'http://' + value;
    }
    if(value.substr(value.length-1, 1) != '/'){
        value = value + '/';
    }
    return this.optional(element) || /^(http|https|ftp):\/\/[a-z0-9]+([\-\.]{1}[a-z0-9]+)*\.[a-z]{2,5}(:[0-9]{1,5})?(\/.*)?$/i.test(value);
}, "Not valid url.");
         */

		$("#empresa-info_general").validate({
            errorPlacement: function (error, element) {

//				if ($(element).is("[name=pais]") || $(element).is("[name=ciudad]")){
				if (element[0].id == 'id_RUC' || element[0].id == 'id_telefono' || element[0].id == 'id_nombre'){
					$(element).tooltip('destroy');
					$(element).tooltip({
						animation: true,
						placement: "right",
						title: $(error).text(),
						trigger: "manual"
					} );
					$(element).tooltip('show');
				}
				else{
					$(element).tooltip('destroy');
					$(element).tooltip({
						animation: true,
						placement: "right",
						title: $(error).text(),
						trigger: "manual"
					} );
					$(element).tooltip('show');
				}
            },
            success: function (label, element) {
				if ($(element).is("[name=pais]") || $(element).is("[name=ciudad]")){
					$("#id_pais").tooltip('hide');
				}
				else {
					$(element).tooltip('hide');
				}

            },
            rules: {
				nombre: {
					required: true,
				},
				quienes_somos_clone: {
					required: true,
					maxlength: 1000
				},
                RUC: {
                    required: true,
					maxlength: 20,
					digits: true
                },
                telefono: {
                    required: true,
					digits: true,
					maxlength: 20
                },
				website:{
					checkurl: true
				},
				ano_fundacion:{
					digits: true,
					maxlength: 4,
					minlength: 4
				}
            },
            messages: {
				nombre: {
					required: "Este campo es obligatorio",
				},
				quienes_somos_clone: {
					required: "Este campo es obligatorio",
					maxlength: "Este campo no puede superar los 1000 caracteres"
				},
                RUC: {
                    required: "Este campo es obligatorio",
					maxlength: "Este campo no puede superar los 20 caracteres",
					digits: "Este campo solo contiene digitos"
                },
                telefono: {
                    required: "Este campo es obligatorio",
					digits: "Este campo solo contiene digitos",
					maxlength: "Este campo no puede superar los 20 caracteres"
                },
				ano_fundacion:{
					digits: "Este campo solo contiene digitos",
					maxlength: "Este campo debe constar de 4 caracteres",
					minlength: "Este campo debe constar de 4 caracteres"
				}
            }
        });

		AgregarPlaceholders();

	});

	function AgregarPlaceholders(){
		$('#id_ano_fundacion').prop('placeholder','Ej. 2015');
		$('#id_RUC').prop('placeholder','RUC de su empresa');
	}

	function InicializarSelect2(){
		$("#id_pais").select2({
  			placeholder: "Pais",
  			//allowClear: true
		});
		$("#id_ciudad").select2({
  			placeholder: "Ciudad",
  			//allowClear: true
		});

		$("#id_pais").change(function() {
			if($("#id_pais").val() > 0 ){
				$.ajax({
					data: {'pais': $("#id_pais").val()},
					url: '{%url "ciudad-busqueda" %}',
					type: 'get',
					success: function (data) {
						if (data) {
							if (data.length > 0) {
//								var options = '<option value="">Ciudad</option>';
								var options = '';
								for (var i = 0; i < data.length; i++) {
									options += '<option value="' + data[i].pk + '">' + data[i].fields['descripcion'] + '</option>';
								}
								$("#id_ciudad").html(options);
								// $("#id_ciudad option:first").attr('selected', 'selected');
								$("#id_ciudad").select2("val", "");
								$("#id_ciudad").attr('disabled', false);
							}
						}
					}
				});
			}
			/*
			else{
				LlamarValidacionElemento('id_pais');*/
				var options = '';
				$("#id_ciudad").html(options);
				$("#id_ciudad").val("").trigger("change");
				$("#id_ciudad").attr('disabled', false);
			//}
		});
		$("#id_ciudad").change(function() {
			$('#id_ciudad_hidden').val($(this).val());
		});

		IniciarCiudades();
	}

	function IniciarCiudades() {
		$.ajax({
			data: {'pais': $("#id_pais").val()},
			url: '{%url "ciudad-busqueda" %}',
			type: 'get',
			success: function (data) {
				if (data) {
					if (data.length > 0) {
						var options = '';
						for (var i = 0; i < data.length; i++) {
							options += '<option value="' + data[i].pk + '">' + data[i].fields['descripcion'] + '</option>';
						}
						$("#id_ciudad").html(options);
						$("#id_ciudad").val($("#id_ciudad_hidden").val()).trigger("change");
						$("#id_ciudad").attr('disabled', false);
					}
				}
			}

		});
	}


</script>

broderjobs/templates/empresa/mi-empresa-redes-sociales.html
<style>
	.tooltip {
		width: 167px;
	}

	.tooltip-arrow{
		top: 44.1754%;
	}
</style>

<div style="margin:0 50px">
	<form id = "empresa-redes-sociales" class="form-horizontal" action="{% url 'mi-empresa-redes-sociales' %}" method="post">
		{%csrf_token%}
		<div class = "form-group">
			<label class = "control-label bold col-sm-3">facebook</label>
			<div class = "col-sm-9">
				{{ form.facebook }}
			</div>
		</div>
		<div class = "form-group">
			<label class = "control-label bold col-sm-3">Twitter</label>
			<div class = "col-sm-9">
				{{ form.twitter }}
			</div>
		</div>
		<!--<input type="submit" class="btn btn-submit col-md-offset-2">-->
	</form>
</div>
<script>
	$(function(){
        $("#form-modal .modal-title").html('<i class="network"></i> Redes sociales');
        $("#empresa-redes-sociales input").each(function(){
            var $input = $(this);
            $(this).inputmask({
                definitions: {
                    i: {
                        validator: ".",
                        cardinality: 1
                    }
                },
                mask: $input.is("#id_facebook")? "\\www.f\\acebook.co\\m/i{+}" : "\\www.tw\\itter.co\\m/i{+}",
                insertMode: !1,
                autoUnmask: !1
            });
        });
		$.validator.addMethod('checkurl',function(value, element, param){
			if (value){
				return /^(www\.)[A-Za-z0-9_-]+\.+[A-Za-z0-9.\/%&=\?_:;-]+$/.test(value);
			}
			else{
				return true;
			}
		},'URL inválida');

		$("#empresa-redes-sociales").validate({
            errorPlacement: function (error, element) {

				$(element).tooltip('destroy');
				$(element).tooltip({
					animation: true,
					placement: "right",
					title: $(error).text(),
					trigger: "manual"
				} );
				$(element).tooltip('show');
            },
            success: function (label, element) {
				$(element).tooltip('hide');
            },
            rules: {
				facebook: {
					checkurl: true,
				},
				twitter: {
					checkurl: true
				}
            }
        });
	});


</script>