broderjobs/broderjobs/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
# from app.views import error

urlpatterns = [
    #INICIO ESTUDIANTES
    url(r'^', include('main.urls')),

    url(r'^estudiante/', include('estudiante.urls')),

    url(r'^empresa/', include('empresa.urls')),

    url(r'^oportunidad/', include('oportunidad.urls')),

    url(r'^mensaje/', include('mensaje.urls')),

    url(r'^contador_visitas/', include('contador_visitas.urls')),

    url(r'^disc/', include('disc.urls')),

    #ADMIN
    url(r'^brodadminpage/', include(admin.site.urls)),

    url('^', include('django.contrib.auth.urls')),

    #LOGIN WITH SOACIAL
    url(r'^social/', include('social.apps.django_app.urls', namespace='social')),
    url(r'^login-facebook' , 'broderjobs.views.login_facebook', name='login-facebook'),

    url(r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_ROOT, 'show_indexes': settings.DEBUG}),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


handler404 = 'broderjobs.views.error404'

broderjobs/disc/urls.py
from django.conf.urls import patterns, include, url
from . import views

urlpatterns = [
    url(r'^formulario-estudiante/$', 'disc.views.formulario_estudiante', name="disc-formulario-estudiante"),
    url(r'^preguntas-estudiante/$', 'disc.views.preguntas_estudiante', name="disc-preguntas-estudiante"),
    url(r'^respuesta-estudiante/$', 'disc.views.respuesta_estudiante', name="disc-respuesta-estudiante"),
    url(r'^finalizo-estudiante/$', 'disc.views.finalizo_estudiante', name="disc-finalizo-estudiante"),
]

broderjobs/estudiante/urls.py
from django.conf.urls import patterns, include, url
from . import views


urlpatterns = [
	url(r'^registro-cv/', 'estudiante.views.registro_cv', name='registro-cv'),

	url(r'^mi-cv/resumen/$', views.ResumenView.as_view(), name="mi-cv-resumen"),

	url(r'^mi-cv/foto/$', views.FotoView.as_view(), name="mi-cv-foto"),

	url(r'^mi-cv/info-personal/$', views.InfoPersonalView.as_view(), name="mi-cv-info-personal"),

	url(r'^mi-cv/disponibilidad/$', views.DisponibilidadView.as_view(), name="mi-cv-disponibilidad"),

	url(r'^mi-cv/idioma/$', views.IdiomaView.as_view(), name="mi-cv-idioma"),

	url(r'^mi-cv/conocimiento/$', views.ConocimientoView.as_view(), name="mi-cv-conocimiento"),
	
	url(r'^mi-cv/actividad-extra/(?P<id>\d+)/$', views.ActividadExtraView.as_view(), name="mi-cv-actividad-extra-editar"),

	url(r'^mi-cv/actividad-extra-crear/$', views.ActividadExtraCrearView.as_view(), name="mi-cv-actividad-extra-crear"),

	url(r'^mi-cv/actividad-extra-eliminar/(?P<pk>\d+)/$', views.ActividadExtraEliminarView.as_view(), name="mi-cv-actividad-extra-eliminar"),

	url(r'^mi-cv/experiencia/(?P<id>\d+)/$', views.ExperienciaView.as_view(), name="mi-cv-experiencia-editar"),

	url(r'^mi-cv/experiencia/$', views.ExperienciaView.as_view(), name="mi-cv-experiencia-editar"),

	url(r'^mi-cv/experiencia-crear/$', views.ExperienciaCrearView.as_view(), name="mi-cv-experiencia-crear"),

	url(r'^mi-cv/experiencia-eliminar/(?P<pk>\d+)/$', views.ExperienciaEliminarView.as_view(), name="mi-cv-experiencia-eliminar"),

	url(r'^mi-cv/voluntariado/(?P<id>\d+)/$', views.VoluntariadoView.as_view(), name="mi-cv-voluntariado-editar"),

	url(r'^mi-cv/voluntariado-crear/$', views.VoluntariadoCrearView.as_view(), name="mi-cv-voluntariado-crear"),

	url(r'^mi-cv/voluntariado-eliminar/(?P<pk>\d+)/$', views.VoluntariadoEliminarView.as_view(), name="mi-cv-voluntariado-eliminar"),

	url(r'^mi-cv/$', views.MiCVView.as_view(), name="mi-cv"),

	url(r'^empresa-lista/$', views.EmpresaListaView.as_view(), name="estudiante-empresa-lista"),

	url(r'^empresa-busqueda/$', views.EmpresaBusquedaView.as_view(), name="estudiante-empresa-busqueda"),

	url(r'^empresa-detalle/(?P<id>\d+)/$', views.EmpresaDetalleView.as_view(), name="estudiante_empresa_detalle"),

	# url(r'^universidad-busqueda/$', views.UniversidadBusquedaView.as_view(), name="universidad-busqueda"),
    #
	# url(r'^carrera-busqueda/$', views.CarreraBusquedaView.as_view(), name="carrera-busqueda"),

	url(r'^estudiante-empresa-busqueda/$', views.EstudianteEmpresaBusquedaView.as_view(), name="empresa-busqueda"),

	url(r'^estudiante-puesto-busqueda/$', views.EstudiantePuestoBusquedaView.as_view(), name="puesto-busqueda"),

	# url(r'^oportunidad-listar/', 'estudiante.views.oportunidad_listar', name='estudiante-oportunidad-listar'),

	# url(r'^oportunidad-busqueda/$', views.OportunidadBusquedaView.as_view(), name="estudiante-oportunidad-busqueda"),

	# url(r'^oportunidad-cargar-lista/$', 'estudiante.views.oportunidad_cargar_lista', name="estudiante-oportunidad-cargar-lista"),

	url(r'^oportunidad-detalle/(?P<id>\d+)/$', views.OportunidadDetalleView.as_view(), name="estudiante-oportunidad-detalle"),

	url(r'^oportunidad-postular/(?P<id>\d+)/$', views.OportunidadPostularView.as_view(), name="estudiante-oportunidad-postular"),
	# url(r'^oportunidad-postular/$', 'estudiante.views.oportunidad_postular', name="estudiante-oportunidad-postular"),

	url(r'^oportunidades-empresa/(?P<id>\d+)/$', views.OportunidadesEmpresaView.as_view(), name='estudiante-oportunidades-empresa'),

	url(r'^proceso-lista/$', views.ProcesoListaView.as_view(), name="estudiante-proceso-lista"),

	url(r'^proceso-detalle/(?P<id>\d+)/$', views.ProcesoDetalleView.as_view(), name="estudiante-proceso-detalle"),

	url(r'^cv-pdf/(?P<id>\d+)/$', 'estudiante.views.cv_pdf', name='cv-pdf'),

	url(r'^compatibilidad/$', 'estudiante.views.compatibilidad_oportunidad', name='estudiante-compatibilidad'),

	url(r'^oportunidad-cargar-lista/$', 'estudiante.views.oportunidad_cargar_lista', name='estudiante-oportunidad-cargar'),

	url(r'^oportunidad-listar/$', 'estudiante.views.oportunidad_listar', name='estudiante-oportunidad-listar'),

]

handler404 = 'main.views.404_view'

broderjobs/estudiante/models.py
   # coding=utf-8
from django.db import models
from django.contrib.postgres.fields import ArrayField
from django.contrib.auth.models import User
from main.models import Persona, Pais, Ciudad, GradoEstudio, Universidad, Carrera, TipoPuesto, CargaHoraria, Idioma, Conocimiento
from empresa.models import Empresa, Puesto
from main import utils
from datetime import date, datetime

items_registro = utils.estado_registro()

class Estudiante(models.Model):
    items_ciclo = utils.semestre_rango()
    items_ciclo_carrera = utils.semestre_carrera()
    items_anos = utils.anos_rango()

    persona = models.OneToOneField(Persona)
    grado_estudio = models.ForeignKey(GradoEstudio,default=None, null=True, blank=True )
    universidad = models.ForeignKey(Universidad,default=None, null=True, blank=True )
    carrera = models.ForeignKey(Carrera, default=None, null=True, blank=True )
    carrera_referencial = models.CharField(max_length="100", default=None, null=True, blank=True)
    semestre_actual = models.CharField(choices=items_ciclo_carrera, max_length=2, default=None, null=True, blank=True, )
    semestre_inicio_estudio = models.CharField(choices=items_ciclo,max_length=2, default=None, null=True, blank=True)
    ano_inicio_estudio = models.CharField(choices=items_anos, max_length=4, default=None, null=True,  blank=True, )
    semestre_graduacion = models.CharField(choices=items_ciclo, max_length=2, default=None, null=True, blank=True, )
    ano_graduacion= models.CharField(choices=items_anos, max_length=4, default=None, null=True, blank=True)
    pais = models.ForeignKey(Pais, default=None, null=True, blank=True )
    ciudad = models.ForeignKey(Ciudad, default=None, null=True, blank=True )
    carga_horaria = models.ForeignKey(CargaHoraria,default=None,null=True, blank=True )
    tipo_puesto = models.ManyToManyField(TipoPuesto, default=None, blank=True, verbose_name="Tipo Puesto")
    idioma = models.ManyToManyField(Idioma, default=None, blank=True, verbose_name="Idioma")
    conocimiento = models.ManyToManyField(Conocimiento, default=None, blank=True, verbose_name="Conocimiento")
    remuneracion = models.CharField(max_length="50", default=None, null=True, blank=True,  )
    foto = models.ImageField('foto perfil', upload_to='img/%Y/%m/%d', null=True, blank=True)
    foto_facebook_url =  models.URLField(default=None, null=True, blank=True)
    completo_test = models.BooleanField(default=False)

    fecha_creacion = models.DateField(default=datetime.now, null=True, blank=True)
    fecha_modificacion = models.DateField(default=datetime.now, null=True, blank=True)
    estado =  models.CharField(choices=items_registro, max_length=1, default='A', null=True, blank=True)

    def __unicode__(self):
		return unicode(self.persona) or u''

    @property
    def set_foto(self):
        if self.foto:
            return self.foto.url
        else:
            if self.foto_facebook_url:
                return self.foto_facebook_url
            else:
                return "/static/img/profile/profile_default.png"

class Resumen(models.Model):
    estudiante =  models.ForeignKey(Estudiante)
    descripcion = models.TextField(default=None, null=True, blank=True)

    fecha_creacion = models.DateField(default=datetime.now, null=True, blank=True)
    fecha_modificacion = models.DateField(default=datetime.now, null=True, blank=True)
    estado =  models.CharField(choices=items_registro, max_length=1, default='A', null=True, blank=True)

    def __unicode__(self):
		return unicode(self.estudiante) or u''

class ActividadesExtra(models.Model):
    estudiante =  models.ForeignKey(Estudiante)
    descripcion = models.TextField(default=None, null=True, blank=True)
    organizacion = models.CharField(max_length="50", default=None, null=True, blank=True)

    fecha_creacion = models.DateField(default=datetime.now, null=True, blank=True)
    fecha_modificacion = models.DateField(default=datetime.now, null=True, blank=True)
    estado =  models.CharField(choices=items_registro, max_length=1, default='A', null=True, blank=True)

    def __unicode__(self):
		return self.descripcion

class ExperienciaProfesional(models.Model):
    estudiante =  models.ForeignKey(Estudiante, default=None, null=True, blank=True)
    puesto = models.ForeignKey(Puesto, default=None, null=True, blank=True)
    puesto_referencial = models.CharField(max_length="50", default=None, null=True)
    empresa = models.ForeignKey(Empresa, default=None, null=True, blank=True)
    empresa_referencial = models.CharField(max_length="50", default=None, null=True)
    fecha_desde = models.DateField(default=None, null=True, blank=True)
    fecha_hasta = models.DateField(default=None, null=True, blank=True)
    trabajo_actual = models.CharField(max_length=1, default='N',)
    descripcion = models.CharField(max_length="1000", default=None, null=True)

    fecha_creacion = models.DateField(default=datetime.now, null=True, blank=True)
    fecha_modificacion = models.DateField(default=datetime.now, null=True, blank=True)
    estado =  models.CharField(choices=items_registro, max_length=1, default='A', null=True, blank=True)

    def __unicode__(self):
		return unicode(self.estudiante) or u''

class Voluntariado(models.Model):
    estudiante =  models.ForeignKey(Estudiante, default=None, null=True, blank=True)
    cargo = models.CharField(max_length="50", default=None, null=True, blank=True)
    organizacion = models.CharField(max_length="50", default=None, null=True, blank=True)
    fecha_desde = models.DateField(null=True)
    fecha_hasta = models.DateField(default=None, null=True, blank=True)
    voluntariado_actual = models.CharField(max_length=1, default='N')
    descripcion = models.CharField(max_length="1000", default=None, null=True, blank=True)

    fecha_creacion = models.DateField(default=datetime.now, null=True, blank=True)
    fecha_modificacion = models.DateField(default=datetime.now, null=True, blank=True)
    estado =  models.CharField(choices=items_registro, max_length=1, default='A', null=True, blank=True)

    def __unicode__(self):
		return unicode(self.cargo) or u''

class ConocimientoExtra(models.Model):
    descripcion = models.CharField(max_length="50", default=None, null=True, blank=True)
    estudiante = models.ForeignKey(Estudiante, default=None, null=True, blank=True)
    orden = models.IntegerField(null= True, blank= True)
    fecha_creacion = models.DateField(default=datetime.now, null=True, blank=True)
    fecha_modificacion = models.DateField(default=datetime.now, null=True, blank=True)
    estado =  models.CharField(choices=items_registro, max_length=1, default='A', null=True, blank=True)

    class Meta:
        ordering = ["orden"]

    def __unicode__(self):
		return unicode(self.descripcion) or u''

broderjobs/templates/estudiante/base-estudiante.html
<html>
	<head>
		<title>Broder jobs</title>
		<meta content="IE=11.0000" http-equiv="X-UA-Compatible">
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=yes">
        <meta name="HandheldFriendly" content="true">
		{% block css %}
		<link rel="stylesheet" href="/static/css/broder.css">
        <link href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet">

		{% endblock css %}
		<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
        <script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
	<body>
		<header class="principal">
			<div class="centered">
				<a href="oportunidades.html"><img class="logo" src="/static/img/logo.png" alt="Broder jobs" /></a>
				<div class="user">
					<div class="menu" id="menu">
						<i class="arrow-down white"></i>
						<div class="v-line"></div>
                        {% if user.is_authenticated %}
							<a class="name">{{user.first_name|capfirst}}</a>
                        {% endif %}
						<div class="clear"></div>
						<div class="contextual-menu" id="ctx-menu-header">
							<div class="wrapper">
								<div class="pin"></div>
								<ul>
									<li><a href="/estudiante/mi-cv/"><i class="cv"></i><span class="v-line gray"></span><span>Mi CV</span><div class="clear"></div></a></li>
									<li><a href="configuracion.html"><i class="config"></i><span class="v-line gray"></span><span>Configuraci&oacute;n</span><div class="clear"></div></a></li>
									<li><a href="index.html"><i class="exit"></i><span class="v-line gray"></span><span>Salir</span><div class="clear"></div></a></li>
								<ul>
							</div>
						</div>
					</div>
					<img class="portrait" src="/static/img/profile/profile.png" alt="Perfil" />
					<div class="clear"></div>
				</div>
				<div class="options">
					<a class="procesos active" href="misprocesos.html">Procesos<label class="notificaciones">2</label></a>
					<div class="clear"></div>
				</div>
				<div class="clear"></div>
			</div>
		</header>
		<header class="menu">
			<div class="centered">
				<a class="active" href="oportunidades.html">Oportunidades</a>
				<a href="empresas.html">Empresas</a>
				<a href="misprocesos.html">Mis procesos</a>
				<div class="clear"></div>
			</div>
		</header>
		{% block content %}
        {% endblock %}
		{% block popup %}
        {% endblock %}
		
	</body>
</html>
{% block js %}
		<!--<script type="text/javascript" src="/static/js/jquery-1.8.2.min.js"></script>-->
       <script>
			$('#menu').click(function() {
				if ($('#ctx-menu-header').hasClass('active'))
					$('#ctx-menu-header').removeClass('active');
				else
					$('#ctx-menu-header').addClass('active')
			});
		</script>


{% endblock js %}

broderjobs/templates/estudiante/empresa-lista.html
{% extends 'estudiante/base.html' %}
{% load staticfiles %}
{%block css%}
{%endblock%}
{% block content %}
<section class="empresas">
    <div class="centered">
        <input id="busqueda" class="search" type="text" placeholder="Buscar por empresas" />
        <ul class="list" id="datos">

        </ul>
		<div class="clear"></div>
    </div>
</section>

{% endblock content %}
{% block js %}

<script>
   (function(){
	   fnBusqueda();
	   $("#link-empresa").addClass("active");
   })();

	$('#busqueda').keyup(fnBusqueda);
	function fnBusqueda(){
		var busqueda = $('#busqueda').val();
		$.ajax({
			data : {'busqueda':busqueda},
			url: '{%url "estudiante-empresa-busqueda" %}',
			type: 'get',
			success: function(data){
                if (data.length == 0){
                    $("#datos").html('<div id="vacio"><h4 class = "no-results">No se encontraron resultados</h4></div>');
                    return false;
                }
				var html = ""
				for(var i = 0; i<data.length ; i++){
					var url = "{%url 'estudiante_empresa_detalle' 1 %}";
					url = url.replace('1', data[i].id);
                    html += '<li><a class="box" href="'+url+'">';
                    html += '<header><img src="'+ data[i].logo + '"/></header>';
                    html += '<div class="content"><h3 class="link text-uppercase">'+ data[i].nombre+'</h3>';
					html +=	'<label class="descripcion">' + data[i].sector + '</label>';
                    html += '<div class="rating"><span class="rating"></span><label>'+data[i].ranking_general+
							' <span style="font-size: 12px;">('+data[i].total_evaluadores+' <i class="fa fa-user"></i>)</span></label></div></div></a></li>';
				}
				$('#datos').html(html);
			}

		});

        document.ready
	}

</script>

{% endblock js %}

broderjobs/templates/estudiante/mi-cv-actividad-extra-eliminar.html
<form method="post" action="{{ request.build_absolute_uri }}">{% csrf_token %}
    <p>Esta seguro que desea eliminar la actividad extra-acad&eacute;mica en: </p>
	<p> {{ object.organizacion }} como {{ object.descripcion }} </p>
    <!--<p><input type="submit" value="Aceptar" /></p>-->
</form>
</form>
<script>
    $(function(){
        $("#form-modal .modal-title").html('<i class="work"></i> &nbsp;Actividades extra-acad\u00E9micas');
	});
</script>

broderjobs/templates/estudiante/mi-cv-experiencia-editar.html
{% load crispy_forms_tags %}

{{ request.build_absolute_uri }}
<div style="margin: 0 50px">
	<form class="form-horizontal" action="{{ request.build_absolute_uri }}" method="post">
		{% crispy form %}
		<input type="submit" class="btn btn-submit col-md-offset-2">

	</form>
</div>

broderjobs/templates/estudiante/mi-cv-experiencia-eliminar.html
<form method="post" action="{{ request.build_absolute_uri }}">{% csrf_token %}
    <p>Esta seguro que desea eliminar la experiencia en: </p>
	<p>
        {%if object.empresa != None %}
        {{ object.empresa }}
        {%else%}
        {{ object.empresa_referencial }}
        {%endif%}
        como
        {%if object.puesto != None %}
        {{ object.puesto }}
        {%else%}
        {{ object.puesto_referencial }}
        {%endif%}
    </p>
    <!--<p><input type="submit" value="Aceptar" /></p>-->
</form>
</form>
<script>
    $(function(){
        $("#form-modal .modal-title").html('<i class="work"></i> &nbsp;Eliminar Experiencia profesional');
	});
</script>

broderjobs/templates/estudiante/mi-cv-voluntariado.html
<style>
	.modal-dialog{
		width: 55%;
	}
</style>
<div style="margin: 0 50px">
	<form id = "cv-voluntariado" action="{{ request.build_absolute_uri }}" method="post">{%csrf_token%}
		<div class="form-horizontal">
			<div class ="form-group">
				<label class = "col-sm-3">Cargo</label>
				<div class = "col-sm-4">
					{{form.cargo}}
				</div>
				<div class = "col-sm-4">
					{{form.organizacion}}
				</div>
			</div>

			<div class ="form-group">
				<label class = "col-sm-3">Desde / Hasta</label>
				<div class = "col-sm-5">
					{{form.fecha_desde_hidden}}
					{{form.fecha_hasta_hidden}}
					<div class="input-group input-daterange">
						<input id="id_fecha_desde" name="fecha_desde" type="text" class="form-control">
						<span class="input-group-addon">a</span>
						<input id="id_fecha_hasta" name="fecha_hasta" type="text" class="form-control">
					</div>

				</div>
				<div class = "col-sm-4" style="padding-top:7px">
					<input class="col-sm-2" id="id_voluntariado_actual" name="voluntariado_actual" type="checkbox" value="S">
					<label class="col-sm-10" style="padding-left:0px">contin&uacute;o realiz&aacute;ndolo</label>
				</div>
			</div>

		</div>
		<div class = "form-group">
			<label class = "control-label">Describe tus actividades</label>
			<textarea id = "txt-descripcion" name="descripcion_txt" maxlength="1000">{{voluntariado_descripcion}}</textarea>
				{{form.descripcion}}
		</div>
	</form>
</div>

<script>

	$(function(){
//		$(".modal-dialog").css("width", "700px")
        $("#txt-descripcion").on("input", function(){
			$("#id_descripcion").val($("#txt-descripcion").val());
		});

        $('textarea').each(function(){
            $(this).after("<div class = 'textarea-feedback'></div>");
            var enteredText = $(this).val();
            var numberOfLineBreaks = (enteredText.match(/\n/g)||[]).length
            var characterCount = enteredText.length + numberOfLineBreaks;

            var totalText = 1000 - characterCount;
            $(this).next().html(totalText + ' caracteres');
        });

        $('textarea').on("keyup", function() {
            var enteredText = $(this).val();
            var numberOfLineBreaks = (enteredText.match(/\n/g)||[]).length;
            var characterCount = enteredText.length + numberOfLineBreaks;

            var totalText = 1000 - characterCount;
            $(this).next().html(totalText + ' caracteres');
        });

		$("#cv-voluntariado input:not(:checkbox)").addClass("form-control");
		$("#cv-voluntariado select").addClass("form-control");
		$("#cv-voluntariado textarea").addClass("form-control");
		$("#form-modal .modal-title").html('<i class="volunteer"></i> &nbsp;Voluntariado');
		$("#id_descripcion").hide();
		$("#txt-descripcion").on("input", function(){
			$("#id_descripcion").val($("#txt-descripcion").val());
		});

		$("#id_voluntariado_actual").change(function(e){
//			console.log($(this).is(":checked"));
			var isChecked = $(this).is(":checked");

			if(isChecked){
				$("#id_fecha_hasta").prop( "disabled", true )
//				$("#id_fecha_hasta").val('');
				$('#id_fecha_hasta').datepicker('setDate','');
				$('#id_fecha_hasta').datepicker('update');
			}
			else{
				$("#id_fecha_hasta").prop( "disabled", false )
				$("#id_fecha_hasta").removeClass('valid');
			}
		});

//		if($("#id_descripcion").val()){
//			$("#txt-descripcion").val($("#id_descripcion").val());
//		}
		
		var fechaDesde = {};

		if($('#id_fecha_desde').val()){
			fechaDesde = moment($('#id_fecha_desde').val(),'DD/MM/YYYY').format('MM/YYYY');
		}
		else if($('#id_fecha_desde_hidden').val()){
			fechaDesde = moment($('#id_fecha_desde_hidden').val(),'YYYY-MM-DD').format('MM/YYYY');
		}
		else{
			fechaDesde = moment().format('MM/YYYY');
		}

		var fechaHasta = {};
		var voluntariado_actual = '{{voluntariado_actual}}';

		if($('#id_fecha_hasta').val()){
			fechaHasta = moment($('#id_fecha_hasta').val(),'DD/MM/YYYY').format('MM/YYYY');
		}
		else if($('#id_fecha_hasta_hidden').val()){
			fechaHasta = moment($('#id_fecha_hasta_hidden').val(),'YYYY-MM-DD').format('MM/YYYY');
		}
		else{
			if(voluntariado_actual == 'S'){
				fechaHasta = '';
				$("#id_voluntariado_actual").prop( "checked", true );
				$("#id_fecha_hasta").prop( "disabled", true );//
			}
			else{
				fechaHasta = moment().format('MM/YYYY');
			}

		}

		$('#id_fecha_desde').val(fechaDesde);
		$('#id_fecha_hasta').val(fechaHasta);

		$('.input-daterange').datepicker({
				autoclose: true,
				language: 'es',
				format: "mm/yyyy",
				startView: "months",
				minViewMode: "months",
				startDate:"01/1950",
				endDate:'0d'
			});

		$('.input-daterange').datepicker().on('changeDate', function(e) {

			if(e.target.id=='id_fecha_hasta' && $("#id_voluntariado_actual").is(":checked") && $('#id_fecha_hasta').val()){
//				$('#id_fecha_hasta').val('');
				$('#id_fecha_hasta').datepicker('setDate','');
				$('#id_fecha_hasta').datepicker('update');

			}
		});

		InicializarValidaciones();
	});

	function InicializarValidaciones(){

		$.validator.addMethod('validarFecha',function(value, element, param){

			if(element.id == 'id_fecha_desde'){
				if(!value){
					return false;
				}
			}
			else if(element.id == 'id_fecha_hasta'){
				if(!$("#id_voluntariado_actual").is(":checked") && !value){
					return false;
				}
			}
			return true;
		},"Este campo es obligatorio");

		$("form").validate({
//			onfocusout: true,
//			onkeyup:true,
            errorPlacement: function (error, element) {

                $(element).tooltip('destroy');

				if(element[0].id == 'id_organizacion' || element[0].id == 'id_fecha_hasta'){

					$(element).tooltip({
						animation: true,
						placement: "right",
						title: $(error).text(),
						trigger: "manual"
                	} );

				}
				else{
					$(element).tooltip({
						animation: true,
						placement: "left",
						title: $(error).text(),
						trigger: "manual"
					} );
				}

                $(element).tooltip('show');

            },
            success: function (label, element) {
                $(element).tooltip('hide');
            },
            rules: {
				cargo: {
					required: true
                },
				organizacion:{
                    required: true
                },
				descripcion:{
					required: true,
					maxlength: 1000
				},
				fecha_desde:{
					validarFecha:true
				},
				fecha_hasta:{
					validarFecha:true
				}

            },
            messages: {
				cargo: {
					required: "Este campo es obligatorio"
                },
				organizacion:{
                    required: "Este campo es obligatorio"
                },
				descripcion:{
					required: "Este campo es obligatorio",
                    maxlength: "Este campo no puede superar los 1000 caracteres"
                }
            }
        });
	}

</script>